module.exports = {
  FAN_CAP_POWER_CONTROL: 'powerControl',
  FAN_CAP_FAN_SPEED_CONTROL: 'fanSpeedControl',
  FAN_CAP_FAN_SPEED_RPM: 'fanSpeedRpm',
  FAN_CAP_FAN_LEVEL_CONTROL: 'fanLevelControl',
  FAN_CAP_NUMBER_OF_FAN_LEVELS: 'numberOfFanLevels',
  FAN_CAP_OSCILLATION_CONTROL: 'oscillationControl',
  FAN_CAP_OSCILLATION_ANGLE_CONTROL: 'oscillationAngle',
  FAN_CAP_OSCILLATION_ANGLE_RANGE: 'oscillationAngleRange',
  FAN_CAP_OSCILLATION_LEVEL_CONTROL: 'oscillationLevelControl',
  FAN_CAP_OSCILLATION_LEVELS: 'oscillationLevels',
  FAN_CAP_LEFT_RIGHT_MOVE: 'leftRightMove',
  FAN_CAP_NATURAL_MODE: 'naturalMode',
  FAN_CAP_SLEEP_MODE: 'sleepMode',
  FAN_CAP_CHILD_LOCK: 'childLock',
  FAN_CAP_POWER_OFF_TIMER: 'powerOffTimer',
  FAN_CAP_POWER_OFF_TIMER_UNIT: 'powerOffTimerUnit',
  FAN_CAP_BUZZER_CONTROL: 'buzzerControl',
  FAN_CAP_BUZZER_CONTROL_LEVELS: 'buzzerControlLevels',
  FAN_CAP_LED_CONTROL: 'ledControl',
  FAN_CAP_LED_CONTROL_LEVELS: 'ledControlLevels',
  FAN_CAP_USE_TIME_REPORTING: 'useTimeReporting',
  FAN_CAP_IONISER_CONTROL: 'ioniserControl',
  FAN_CAP_TEMPERATURE_REPORTING: 'temperatureReporting',
  FAN_CAP_HUMIDITY_REPORTING: 'humidityReporting',
  FAN_CAP_BUILT_IN_BATTERY: 'builtInBattery',
  FAN_CAP_BATTERY_STATE_REPORTING: 'batteryStateReporting'
};
